# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'taboola' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for taboola
  pod 'TaboolaSDK', '2.1.2'

  target 'taboolaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'taboola-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for taboola-tvOS

  target 'taboola-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
