# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TaboolaReactNativeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaboolaReactNativeExample
  pod 'TaboolaSDK', '2.8.2'

  # target 'TaboolaReactNativeExample-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end


  target 'TaboolaReactNativeExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TaboolaReactNativeExample-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaboolaReactNativeExample-tvOS

  target 'TaboolaReactNativeExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  ## Fix for XCode 12.5 beta
  find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
  "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end